# Generated by Django 5.0 on 2024-02-05 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
        ("scheduler", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdditionalCalendarInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("private", models.BooleanField(default=False)),
                (
                    "calendar",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to="schedule.calendar",
                    ),
                ),
            ],
        ),
    ]
