# Generated by Django 5.0 on 2024-02-01 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0002_alter_donation_donor"),
        ("contact_analytics", "0002_accountprofile_company_phonenumber_delete_contact"),
        ("donor_management", "0003_remove_donor_name_donor_donor_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Donations",
                to="donor_management.donor",
            ),
        ),
        migrations.AlterField(
            model_name="patient",
            name="name",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact_analytics.accountprofile",
            ),
        ),
    ]
