# Generated by Django 5.0 on 2024-03-28 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0006_monetarycampaign_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cause",
            name="campaign_type",
        ),
        migrations.RemoveField(
            model_name="cause",
            name="patients_name",
        ),
    ]
