# Generated by Django 5.0 on 2024-03-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0008_rename_description_patient_notes_patient_causes"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name="cause",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="hospital",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="illness",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="patient",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
