# Generated by Django 5.0 on 2024-03-29 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0009_cause_title_alter_cause_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cause",
            name="title",
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
