# Generated by Django 5.0 on 2024-04-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0010_alter_cause_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donation",
            name="campaign_type",
        ),
        migrations.AddField(
            model_name="donation",
            name="campaign",
            field=models.ManyToManyField(blank=True, to="campaigns.monetarycampaign"),
        ),
        migrations.AddField(
            model_name="monetarycampaign",
            name="photo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
