# Generated by Django 5.0 on 2024-04-11 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0012_alter_monetarycampaign_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monetarycampaign",
            name="goal",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.DeleteModel(
            name="Donation",
        ),
    ]
