# Generated by Django 5.0 on 2024-06-18 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0014_rename_patient_beneficairies_alter_cause_title"),
        ("contact_analytics", "0017_accountprofile_website_phonenumber_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=255)),
                ("health_status", models.TextField(blank=True, null=True)),
                ("location", models.TextField(blank=True, null=True)),
                ("special_needs", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommunityDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255)),
                ("community_name", models.CharField(max_length=255)),
                ("location", models.TextField(blank=True, null=True)),
                ("key_objectives", models.TextField(blank=True, null=True)),
                ("impact_metrics", models.TextField(blank=True, null=True)),
                ("funding_sources", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DisabilitySupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "support_type",
                    models.CharField(
                        choices=[
                            ("Financial Aid", "Financial Aid"),
                            ("Equipment", "Equipment"),
                            ("Training", "Training"),
                        ],
                        max_length=50,
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("number_of_beneficiaries", models.IntegerField(default=0)),
                ("key_services_provided", models.TextField(blank=True, null=True)),
                ("funding_sources", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EducationalInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("Primary", "Primary"),
                            ("Secondary", "Secondary"),
                            ("University", "University"),
                            ("Orphanage", "Orphanage"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_students", models.IntegerField(default=0)),
                ("programs_offered", models.TextField(blank=True, null=True)),
                ("accreditation_details", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmergencyRelief",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relief_type",
                    models.CharField(
                        choices=[
                            ("Natural Disaster", "Natural Disaster"),
                            ("Conflict", "Conflict"),
                            ("Pandemic", "Pandemic"),
                        ],
                        max_length=50,
                    ),
                ),
                ("area_covered", models.TextField(blank=True, null=True)),
                ("contact_organization", models.TextField(blank=True, null=True)),
                ("number_of_beneficiaries", models.IntegerField(default=0)),
                ("key_services_provided", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnvironmentalProtection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("organization_name", models.CharField(max_length=255)),
                ("project_name", models.CharField(max_length=255)),
                ("location", models.TextField(blank=True, null=True)),
                (
                    "conservation_type",
                    models.CharField(
                        choices=[
                            ("Reforestation", "Reforestation"),
                            ("Wildlife Protection", "Wildlife Protection"),
                        ],
                        max_length=50,
                    ),
                ),
                ("impact_metrics", models.TextField(blank=True, null=True)),
                ("funding_sources", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthCareInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("Hospital", "Hospital"),
                            ("Clinic", "Clinic"),
                            ("Health Center", "Health Center"),
                            ("Senior Homes", "Senior Homes"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_beds", models.IntegerField(default=0)),
                ("specializations", models.TextField(blank=True, null=True)),
                ("operating_hours", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialWelfareProgram",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_name", models.CharField(max_length=255)),
                (
                    "program_type",
                    models.CharField(
                        choices=[
                            ("Food Aid", "Food Aid"),
                            ("Shelter", "Shelter"),
                            ("Education", "Education"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_population", models.TextField(blank=True, null=True)),
                ("funding_sources", models.TextField(blank=True, null=True)),
                ("key_activities", models.TextField(blank=True, null=True)),
                ("impact_metrics", models.TextField(blank=True, null=True)),
                (
                    "profile",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
    ]
