# Generated by Django 5.0 on 2024-06-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0015_animal_communitydevelopment_disabilitysupport_and_more"),
        ("contact_analytics", "0017_accountprofile_website_phonenumber_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="HealthCareInstitution",
            new_name="temp",
        ),
    ]
