# Generated by Django 5.0 on 2024-06-19 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0017_rename_temp_healthcareinstitution"),
        ("contact_analytics", "0017_accountprofile_website_phonenumber_name_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Beneficairies",
            new_name="HealthcarePatient",
        ),
    ]
