# Generated by Django 5.0 on 2024-06-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0018_rename_beneficairies_healthcarepatient"),
        ("contact_analytics", "0018_alter_accountprofile_benficiary"),
    ]

    operations = [
        migrations.AddField(
            model_name="monetarycampaign",
            name="beneficiaries",
            field=models.ManyToManyField(
                blank=True,
                related_name="campaigns",
                to="contact_analytics.accountprofile",
            ),
        ),
        migrations.AlterField(
            model_name="monetarycampaign",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_campaigns",
                to="contact_analytics.accountprofile",
            ),
        ),
    ]
