# Generated by Django 5.0 on 2024-06-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0019_monetarycampaign_beneficiaries_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disabilitysupport",
            name="support_type",
            field=models.CharField(
                choices=[
                    ("FINANCIAL AID", "Financial Aid"),
                    ("EQUIPMENT", "Equipment"),
                    ("TRAINING", "Training"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="educationalinstitution",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("PRIMARY", "Primary"),
                    ("SECONDARY", "Secondary"),
                    ("UNIVERSITY", "University"),
                    ("ORPHANAGE", "Orphanage"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="emergencyrelief",
            name="relief_type",
            field=models.CharField(
                choices=[
                    ("NATURAL DISASTER", "Natural Disaster"),
                    ("CONFLICT", "Conflict"),
                    ("PANDEMIC", "Pandemic"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="environmentalprotection",
            name="conservation_type",
            field=models.CharField(
                choices=[
                    ("REFORESTATION", "Reforestation"),
                    ("WEILDLIFE PROTECTION", "Wildlife Protection"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="healthcareinstitution",
            name="institution_type",
            field=models.CharField(
                choices=[
                    ("HOSPITAL", "Hospital"),
                    ("CLINIC", "Clinic"),
                    ("HEALTH CENTER", "Health Center"),
                    ("SENIOR HOMES", "Senior Homes"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="socialwelfareprogram",
            name="program_type",
            field=models.CharField(
                choices=[
                    ("FOOD AID", "Food Aid"),
                    ("SHELTER", "Shelter"),
                    ("EDUCATION", "Education"),
                ],
                max_length=50,
            ),
        ),
    ]
