# Generated by Django 5.0 on 2024-06-19 18:09

import apps.campaigns.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0021_remove_healthcarepatient_causes_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "upload",
                    models.FileField(
                        upload_to=apps.campaigns.models.user_directory_path
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="monetarycampaign",
            name="photo",
        ),
        migrations.AddField(
            model_name="monetarycampaign",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monetarycampaign",
            name="last_edited",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="monetarycampaign",
            name="last_edited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="edited_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="monetarycampaign",
            name="photos",
            field=models.ManyToManyField(
                blank=True, related_name="campaigns", to="campaigns.photo"
            ),
        ),
    ]
