# Generated by Django 5.0 on 2024-06-19 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0022_photo_remove_monetarycampaign_photo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="upload",
            new_name="file",
        ),
    ]
