# Generated by Django 5.0 on 2024-06-20 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0026_alter_monetarycampaign_start_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="monetarycampaign",
            name="beneficiaries",
        ),
    ]
