# Generated by Django 5.0 on 2024-06-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0028_healthcarepatient_campaigns"),
    ]

    operations = [
        migrations.AddField(
            model_name="animal",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True, related_name="ANIMAL", to="campaigns.monetarycampaign"
            ),
        ),
        migrations.AddField(
            model_name="communitydevelopment",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="COMMUNITY_DEVELOPMENT",
                to="campaigns.monetarycampaign",
            ),
        ),
        migrations.AddField(
            model_name="disabilitysupport",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="DISABILITY_SUPPORT",
                to="campaigns.monetarycampaign",
            ),
        ),
        migrations.AddField(
            model_name="educationalinstitution",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="EDUCATIONAL_INSTITUTION",
                to="campaigns.monetarycampaign",
            ),
        ),
        migrations.AddField(
            model_name="emergencyrelief",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="EMERGENCY_RELIEF",
                to="campaigns.monetarycampaign",
            ),
        ),
        migrations.AddField(
            model_name="environmentalprotection",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="ENVIRONMENTAL_PROTECTION",
                to="campaigns.monetarycampaign",
            ),
        ),
        migrations.AddField(
            model_name="healthcareinstitution",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="HEALTHCARE_INSTITUTION",
                to="campaigns.monetarycampaign",
            ),
        ),
        migrations.AddField(
            model_name="socialwelfareprogram",
            name="campaigns",
            field=models.ManyToManyField(
                blank=True,
                related_name="SOCIAL_WELFARE_PROGRAM",
                to="campaigns.monetarycampaign",
            ),
        ),
    ]
