# Generated by Django 5.0 on 2024-06-20 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0029_animal_campaigns_communitydevelopment_campaigns_and_more"),
        ("users", "0010_user_timezone"),
    ]

    operations = [
        migrations.AddField(
            model_name="monetarycampaign",
            name="institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="users.institution",
            ),
        ),
    ]
