# Generated by Django 5.0 on 2024-06-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0030_monetarycampaign_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monetarycampaign",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
