# Generated by Django 5.0 on 2024-06-24 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0031_alter_monetarycampaign_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="healthcarepatient",
            name="hospital",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="healthcarepatient",
            name="illness",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
