# Generated by Django 5.0 on 2024-02-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schedule", "0014_use_autofields_for_pk"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendars",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="schedule.calendar"
            ),
        ),
    ]
