# Generated by Django 5.0 on 2024-06-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_is_bsystems_user_user_is_instituition_admin"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [
                    ("approve_institution", "Can approve institution"),
                    ("change_institution_status", "Can change institution status"),
                    ("approve_campaign", "Can approve campaign"),
                    ("change_campaign_status", "Can change campaign status"),
                    ("create_other_users", "Can create other users"),
                    ("create_campaigns", "Can create campaigns"),
                    ("approve_other_campaigns", "Can approve other campaigns"),
                    ("create_tasks", "Can create tasks"),
                    ("create_events", "Can create events"),
                    (
                        "view_all_tasks_campaigns_events",
                        "Can view all tasks, campaigns, and events",
                    ),
                    ("change_user_status", "Can change user status"),
                    ("change_own_password", "Can change own password"),
                    ("change_other_passwords", "Can change other users' passwords"),
                ]
            },
        ),
        migrations.RenameField(
            model_name="user",
            old_name="is_instituition_admin",
            new_name="is_institution_admin",
        ),
        migrations.AddField(
            model_name="user",
            name="is_instituition_user",
            field=models.BooleanField(
                default=False, verbose_name="Is Institution User"
            ),
        ),
    ]
