# Generated by Django 5.0 on 2024-06-19 01:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_institution_user_institution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institution",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
