# Generated by Django 5.0 on 2024-06-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_timezone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bsystems_user",
            field=models.BooleanField(
                default=False, null=True, verbose_name="Is Bsystems User"
            ),
        ),
    ]
