# Generated by Django 5.0 on 2024-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_bsystems_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bsystems_user",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is Bsystems User"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution_admin",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Is Institution Admin"
            ),
        ),
    ]
