# Generated by Django 5.0 on 2024-06-20 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_user_bsystems_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bsystems_user",
            field=models.BooleanField(
                db_default=models.Value(False), verbose_name="Is Bsystems User"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="institution_admin",
            field=models.BooleanField(
                db_default=models.Value(False), verbose_name="Is Institution Admin"
            ),
        ),
    ]
