# Generated by Django 5.0 on 2024-01-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Donor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "donor_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Individual"),
                            ("Institution", "Institution"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "amount_donated",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("institution", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("notes", models.TextField(max_length=250, verbose_name="Notes")),
            ],
        ),
        migrations.CreateModel(
            name="LeadAcquisition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "acquisition",
                    models.CharField(max_length=100, verbose_name="Lead Acquisition"),
                ),
                (
                    "Donor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor_management.donor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100, verbose_name="Lead Type")),
                (
                    "Donor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor_management.donor",
                    ),
                ),
            ],
        ),
    ]
