# Generated by Django 5.0 on 2024-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor_management", "0001_initial"),
        ("schedule", "0014_use_autofields_for_pk"),
    ]

    operations = [
        migrations.AddField(
            model_name="donor",
            name="attended_events",
            field=models.ManyToManyField(blank=True, to="schedule.event"),
        ),
    ]
