# Generated by Django 5.0 on 2024-02-09 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contact_analytics",
            "0003_rename_companies_accountprofile_organizations_and_more",
        ),
        ("donor_management", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="donor_type",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="institution",
        ),
        migrations.AddField(
            model_name="donor",
            name="type_of_donor",
            field=models.CharField(
                choices=[
                    ("None", "None"),
                    ("Ind", "Individual"),
                    ("Ins", "Institution"),
                ],
                default="None",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_profile",
                to="contact_analytics.accountprofile",
            ),
        ),
    ]
