# Generated by Django 5.0 on 2024-03-01 16:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_analytics",
            "0004_remove_phonenumber_company_accountprofile_company_and_more",
        ),
        ("donor_management", "0003_remove_donor_name_donor_donor_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donor",
            name="address",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="country",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="email",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="institution",
        ),
        migrations.RemoveField(
            model_name="donor",
            name="region",
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="donor_profile",
                to="contact_analytics.accountprofile",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_type",
            field=models.CharField(
                choices=[("Individual", "Individual"), ("Institution", "Institution")],
                default="Individual",
                max_length=100,
            ),
        ),
    ]
