# Generated by Django 5.0 on 2024-03-29 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor_management", "0006_rename_donor_leadacquisition_donor_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leadtype",
            name="donor",
        ),
        migrations.RemoveField(
            model_name="leadtype",
            name="type",
        ),
        migrations.AddField(
            model_name="leadtype",
            name="lead_type",
            field=models.CharField(
                choices=[
                    ("broad_base_donor", "Broad Base Donor"),
                    ("mid_range_donor", "Mid Range Donor"),
                    ("major_donor", "Major Donor"),
                ],
                default="broad_base_donor",
                max_length=100,
                verbose_name="Lead Type",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="donor_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="donor_management.leadtype",
            ),
        ),
        migrations.AlterField(
            model_name="donor",
            name="notes",
            field=models.TextField(max_length=500, verbose_name="Notes"),
        ),
        migrations.DeleteModel(
            name="LeadAcquisition",
        ),
    ]
