# Generated by Django 5.0 on 2024-03-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "donor_management",
            "0007_remove_leadtype_donor_remove_leadtype_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="donor",
            name="notes",
            field=models.TextField(
                blank=True, max_length=500, null=True, verbose_name="Notes"
            ),
        ),
    ]
