# Generated by Django 5.0 on 2024-04-11 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0013_alter_monetarycampaign_goal_delete_donation"),
        ("donor_management", "0008_alter_donor_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="GHC", max_length=100)),
                ("date", models.DateField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[("IN", "Incoming"), ("OUT", "Outgoing")], max_length=3
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ManyToManyField(blank=True, to="campaigns.monetarycampaign"),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="campaigns.patient",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense",
                        to="donor_management.transaction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "campaign",
                    models.ManyToManyField(blank=True, to="campaigns.monetarycampaign"),
                ),
                (
                    "donor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donations",
                        to="donor_management.donor",
                    ),
                ),
                (
                    "transaction",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="donation",
                        to="donor_management.transaction",
                    ),
                ),
            ],
        ),
    ]
