# Generated by Django 5.0 on 2024-04-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donor_management", "0009_transaction_expense_donation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
