# Generated by Django 5.0 on 2024-02-08 09:52

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("given_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PATIENT", "Patient"),
                            ("INSTITUTION", "Institution"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        default="GH",
                        max_length=2,
                        null=True,
                        verbose_name="Country",
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Company"),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Company Address"),
                ),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="Company District"),
                ),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="Company Region"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Donor"),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("notes", models.TimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.company",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
    ]
