# Generated by Django 5.0 on 2024-01-24 12:23

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("donor_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nameOfDonor",
                    models.CharField(max_length=50, verbose_name="Name of Donor"),
                ),
                (
                    "meetingStatus",
                    models.CharField(max_length=50, verbose_name="Meeting Status"),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None, verbose_name="Phone"
                    ),
                ),
                ("email", models.EmailField(max_length=50, verbose_name="Email")),
                (
                    "Donor",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="donor_management.donor",
                    ),
                ),
            ],
        ),
    ]
