# Generated by Django 4.2.6 on 2023-12-14 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("donor_management", "0002_alter_leadacquisition_donor_alter_leadtype_donor"),
        ("contact_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="Donor",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="donor_management.donor",
            ),
        ),
    ]
