# Generated by Django 5.0 on 2024-02-01 11:53

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("given_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PATIENT", "Patient"),
                            ("INSTITUTION", "Institution"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                ("region", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Company"),
                ),
                (
                    "address",
                    models.CharField(max_length=100, verbose_name="Company Address"),
                ),
                (
                    "district",
                    models.CharField(max_length=100, verbose_name="Company District"),
                ),
                (
                    "region",
                    models.CharField(max_length=100, verbose_name="Company Region"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhoneNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Name of Donor"),
                ),
                (
                    "number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=128, region=None
                    ),
                ),
                ("notes", models.TimeField(auto_now=True)),
                (
                    "Company",
                    models.ForeignKey(
                        default=None,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.company",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contact_analytics.accountprofile",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
