# Generated by Django 5.0 on 2024-02-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_analytics", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="companies",
            field=models.ManyToManyField(
                related_name="account_profiles", to="contact_analytics.company"
            ),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="email",
            field=models.EmailField(default="youremail@example.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="role",
            field=models.CharField(
                choices=[("PATIENT", "Patient"), ("INSTITUTION", "Institution")],
                default="PATIENT",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact_analytics.company",
            ),
        ),
    ]
