# Generated by Django 5.0 on 2024-02-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0002_accountprofile_company_phonenumber_delete_contact"),
    ]

    operations = [
        migrations.RenameField(
            model_name="phonenumber",
            old_name="Company",
            new_name="company",
        ),
    ]
