# Generated by Django 4.2.6 on 2023-12-14 14:31

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("contact_analytics", "0002_contact_donor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=50, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="meetingStatus",
            field=models.CharField(max_length=50, verbose_name="Meeting Status"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="nameOfDonor",
            field=models.CharField(max_length=50, verbose_name="Name of Donor"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, region=None, verbose_name="Phone"
            ),
        ),
    ]
