# Generated by Django 5.0 on 2024-02-09 23:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "contact_analytics",
            "0003_rename_companies_accountprofile_organizations_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountprofile",
            old_name="organizations",
            new_name="organization",
        ),
    ]
