# Generated by Django 5.0 on 2024-02-12 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact_analytics", "0004_rename_organizations_accountprofile_organization"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="organization",
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="email",
            field=models.EmailField(
                blank=True, default="youremail@example.com", max_length=254
            ),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_number",
                to="contact_analytics.accountprofile",
            ),
        ),
    ]
