# Generated by Django 5.0 on 2024-03-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_analytics",
            "0004_remove_phonenumber_company_accountprofile_company_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="given_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="accountprofile",
            name="last_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
