# Generated by Django 5.0 on 2024-03-01 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0005_alter_accountprofile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="contact_analytics.company",
            ),
        ),
    ]
