# Generated by Django 5.0 on 2024-03-20 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0006_alter_accountprofile_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phonenumber",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="phone_number",
                to="contact_analytics.accountprofile",
            ),
        ),
    ]
