# Generated by Django 5.0 on 2024-03-29 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0007_alter_phonenumber_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="name",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
