# Generated by Django 5.0 on 2024-03-29 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0008_alter_accountprofile_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="phonenumber",
            name="name",
        ),
    ]
