# Generated by Django 5.0 on 2024-03-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0009_remove_phonenumber_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="profile_photo",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
