# Generated by Django 5.0 on 2024-05-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "contact_analytics",
            "0011_accountprofile_is_active_accountprofile_is_patient",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PATIENT", "Patient"),
                    ("INSTITUTION", "Institution"),
                    ("EDUCATIONAL_INSTITUTION", "Educational Institution"),
                    ("HEALTHCARE_INSTITUTION", "Healthcare Institution"),
                    ("HEALTHCARE_PATIENT", "Healthcare Patient"),
                    ("ANIMALS", "Animals"),
                    ("SOCIAL_WELFARE_PROGRAMS", "Social Welfare Programs"),
                    ("EMERGENCY_RELIEF", "Emergency Relief"),
                    (
                        "ENVIRONMENTAL_PROTECTION",
                        "Environmental Protection/Conversation",
                    ),
                    ("COMMUNITY_DEVELOPMENT", "Community Development"),
                    ("DISABILITY_SUPPORT", "Disability Support"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
