# Generated by Django 5.0 on 2024-06-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0013_rename_role_accountprofile_benficiary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="benficiary",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDUCATIONAL_INSTITUTION", "Educational Institution"),
                    ("HEALTHCARE_INSTITUTION", "Healthcare Institution"),
                    ("HEALTHCARE_PATIENT", "Healthcare Patient"),
                    ("ANIMALS", "Animals"),
                    ("SOCIAL_WELFARE_PROGRAMS", "Social Welfare Programs"),
                    ("EMERGENCY_RELIEF", "Emergency Relief"),
                    (
                        "ENVIRONMENTAL_PROTECTION",
                        "Environmental Protection/Conversation",
                    ),
                    ("COMMUNITY_DEVELOPMENT", "Community Development"),
                    ("DISABILITY_SUPPORT", "Disability Support"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
