# Generated by Django 5.0 on 2024-06-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_analytics",
            "0015_rename_is_patient_accountprofile_is_beneficiary_and_more",
        ),
        ("users", "0008_institution_user_institution"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="associated_institutions",
        ),
        migrations.AddField(
            model_name="accountprofile",
            name="associated_institution",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="contacts",
                to="users.institution",
            ),
        ),
    ]
