# Generated by Django 5.0 on 2024-06-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_analytics",
            "0016_remove_accountprofile_associated_institutions_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accountprofile",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="phonenumber",
            name="primary_contact",
            field=models.BooleanField(default=False),
        ),
    ]
