# Generated by Django 5.0 on 2024-06-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0017_accountprofile_website_phonenumber_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accountprofile",
            name="benficiary",
            field=models.CharField(
                blank=True,
                choices=[
                    ("EDUCATIONAL_INSTITUTION", "Educational Institution"),
                    ("HEALTHCARE_INSTITUTION", "Healthcare Institution"),
                    ("HEALTHCARE_PATIENT", "Healthcare Patient"),
                    ("ANIMAL", "Animal"),
                    ("SOCIAL_WELFARE_PROGRAM", "Social Welfare Program"),
                    ("EMERGENCY_RELIEF", "Emergency Relief"),
                    (
                        "ENVIRONMENTAL_PROTECTION",
                        "Environmental Protection/Conservation",
                    ),
                    ("COMMUNITY_DEVELOPMENT", "Community Development"),
                    ("DISABILITY_SUPPORT", "Disability Support"),
                ],
                max_length=250,
                null=True,
            ),
        ),
    ]
