# Generated by Django 5.0 on 2024-06-19 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0018_alter_accountprofile_benficiary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accountprofile",
            name="is_beneficiary",
        ),
    ]
