# Generated by Django 5.0 on 2024-06-19 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0019_remove_accountprofile_is_beneficiary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountprofile",
            old_name="benficiary",
            new_name="beneficiary",
        ),
    ]
