# Generated by Django 5.0 on 2024-06-19 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contact_analytics", "0020_rename_benficiary_accountprofile_beneficiary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accountprofile",
            old_name="beneficiary",
            new_name="beneficiary_type",
        ),
    ]
