# Generated by Django 5.0 on 2024-06-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "contact_analytics",
            "0021_rename_beneficiary_accountprofile_beneficiary_type",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="phonenumber",
            name="relation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="phonenumber",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
